import type { UiContext, UiNode, UiTreeItem, ViewLine, ViewSegment } from "@amira/api"
import type {
  DashboardAgent,
  DashboardFile,
  DashboardPhase,
  DashboardSource,
  DashboardStatus,
} from "./source.ts"

const part = (text: string, kind: ViewSegment["kind"] = "text"): ViewSegment => ({ text, kind })
const segments = (parts: ViewSegment[]): ViewLine => ({ kind: "segments", parts })
const text = (lines: ViewLine[], id?: string): UiNode => ({ type: "text", id, lines })
export const clock = (at?: number) =>
  at === undefined ? "--:--:--" : new Date(at).toISOString().slice(11, 19)
export const duration = (ms?: number) => (ms === undefined ? "—" : `${Math.max(0, Math.round(ms / 1000))}s`)
export const mark: Record<DashboardStatus, string> = {
  queued: "◌",
  running: "●",
  idle: "○",
  paused: "‖",
  done: "✓",
  failed: "✗",
  stopped: "⊘",
}
export const tone = (status: DashboardStatus): ViewSegment["kind"] =>
  status === "failed" ? "error" : status === "done" ? "success" : status === "running" ? "accent" : "muted"

/** Cell-aware fields, including CJK/emoji. No ANSI styling is generated by the extension. */
function field(value: string, width: number): string {
  // biome-ignore lint/suspicious/noControlCharactersInRegex: sanitize source text before cell measurement
  const clean = value.replace(/[\x00-\x1f\x7f-\x9f]/g, " ")
  if (Bun.stringWidth(clean) <= width) return clean + " ".repeat(width - Bun.stringWidth(clean))
  let result = ""
  for (const { segment } of new Intl.Segmenter().segment(clean)) {
    if (Bun.stringWidth(result + segment) > width - 1) break
    result += segment
  }
  return `${result}…${" ".repeat(Math.max(0, width - Bun.stringWidth(result) - 1))}`
}

export function phaseInfo(phase: DashboardPhase, now: number) {
  const agents = phase.groups.flatMap((group) => group.agents)
  const statuses = phase.groups.flatMap((group) =>
    group.status ? [group.status] : group.agents.map((agent) => agent.status),
  )
  const group = phase.groups.length === 1 ? phase.groups[0] : undefined
  const status =
    phase.status ??
    group?.status ??
    (["running", "failed", "paused", "queued", "idle", "stopped"] as const).find((status) =>
      statuses.includes(status),
    ) ??
    (statuses.length ? "done" : "queued")
  const starts = [...agents, ...phase.groups].flatMap((item) =>
    item.startedAt === undefined ? [] : [item.startedAt],
  )
  const startedAt = phase.startedAt ?? (starts.length ? Math.min(...starts) : undefined)
  const ends = agents.flatMap((agent) =>
    agent.startedAt === undefined || agent.durationMs === undefined
      ? []
      : [agent.startedAt + agent.durationMs],
  )
  const durationMs =
    phase.durationMs ??
    group?.durationMs ??
    (startedAt === undefined
      ? undefined
      : status === "running" || status === "paused"
        ? now - startedAt
        : ends.length === agents.length && ends.length
          ? Math.max(...ends) - startedAt
          : undefined)
  const steps =
    phase.stepCount ??
    (phase.groups.every((group) => group.stepCount !== undefined) && phase.groups.length
      ? phase.groups.reduce((sum, group) => sum + group.stepCount!, 0)
      : undefined)
  const description =
    phase.description ??
    group?.description ??
    (status === "done"
      ? [
          ...(steps === undefined ? [] : [`${steps} steps`]),
          `${agents.length} ${agents.length === 1 ? "agent" : "agents"}`,
          ...(durationMs === undefined ? [] : [duration(durationMs)]),
        ].join(" · ")
      : status === "queued"
        ? "queued"
        : (agents.find((agent) => agent.status === status)?.task ?? status))
  return { agents, status, startedAt, durationMs, description, ref: phase.ref ?? group?.ref ?? phase.id }
}

function fileParts(file: DashboardFile, width: number): ViewSegment[] {
  const counts = [
    file.added === undefined ? "" : `+${file.added}`,
    file.removed === undefined ? "" : `-${file.removed}`,
  ]
    .filter(Boolean)
    .join("  ")
  return [
    part(field(file.path, Math.max(1, width - (counts ? counts.length + 3 : 0)))),
    ...(counts ? [part(`   ${counts}`, "success")] : []),
  ]
}

/** A shared frame composed from selectable card heads and display-only semantic bodies. */
export function timeline(source: DashboardSource, ctx: UiContext, selected?: string): UiNode {
  const phases = source.snapshot().phases
  if (!phases.length)
    return text(
      [
        {
          kind: "text",
          text:
            source.snapshot().warning ??
            source.snapshot().note ??
            "No agents yet. Start a task with sub-agents, then return here.",
        },
      ],
      "empty",
    )
  const narrow = ctx.width < 110
  const selectedPhase =
    phases.find(
      (phase) =>
        `phase:${phase.id}` === ctx.state.selected.timeline ||
        phase.groups.some((group) => group.agents.some((agent) => agent.id === selected)),
    ) ??
    phases.find((phase) => phaseInfo(phase, ctx.now).status === "running") ??
    phases[0]
  const expanded = ctx.state.expanded.timeline
  const open = (key: string) => expanded === undefined || expanded.includes(key)
  // The host reserves two cells for selection and twelve for time/status. The box starts at 17.
  const innerWidth = Math.max(1, ctx.width - 22)
  const frame = (left: string, right: string): UiNode =>
    text([segments([part(` ${left}${"─".repeat(innerWidth + 2)}${right}`, "muted")])])
  const bodyLine = (node: UiNode): UiNode => ({
    type: "row",
    children: [
      { size: 3, node: text([segments([part(" │ ", "muted")])]) },
      { node },
      { size: 3, node: text([segments([part(" │ ", "muted")])]) },
    ],
  })
  const items: UiTreeItem[] = []
  for (const [phaseIndex, phase] of phases.entries()) {
    const info = phaseInfo(phase, ctx.now)
    const key = `phase:${phase.id}`
    const showCards = open(key) && info.agents.length > 0 && (!narrow || phase === selectedPhase)
    const name = `${phase.name}${info.agents.length > 1 && !phase.name.includes("×") ? ` ×${info.agents.length}` : ""}`
    items.push({
      key,
      lead: [
        part(`${clock(info.startedAt)}  ${info.status === "queued" ? " " : mark[info.status]}`, "muted"),
      ],
      node: [part(info.status === "running" ? "◉" : "○", tone(info.status))],
      row: [
        part(`${field(name, narrow ? 14 : 15)} `, info.status === "running" ? "accent" : "text"),
        part(info.description, "muted"),
        ...(info.status === "running" ? [part(`   ▏running ${duration(info.durationMs)}▕`, "accent")] : []),
      ],
      aside: [part(`${narrow ? "" : `${info.ref}  `}${showCards ? "▾" : "▸"}`, "muted")],
      rail: true,
      expandable: info.agents.length > 0,
      underline: !showCards,
      ...(showCards ? { detail: frame("╭", "╮") } : {}),
    })
    if (!showCards) continue
    for (const [index, agent] of info.agents.entries()) {
      const last = index === info.agents.length - 1
      const foldedFooter = last && !open(`agent:${agent.id}`)
      const count = `${info.agents.length} ${info.agents.length === 1 ? "agent" : "agents"} · ${info.agents.filter((agent) => agent.status === "running").length} running`
      const detail = source.details(agent.id)
      const progress =
        agent.progress === undefined || !Number.isFinite(agent.progress)
          ? undefined
          : Math.max(0, Math.min(1, agent.progress))
      const filled = Math.round((progress ?? 0) * (narrow ? 6 : 14))
      const bar = "━".repeat(filled) + "─".repeat((narrow ? 6 : 14) - filled)
      const can = (action: DashboardAgent["actions"][number]) =>
        !!source.act && agent.actions.includes(action)
      const labels = [
        ...(agent.files.length ? [part("Open diff", "accent")] : []),
        ...(can("pause") || can("resume") ? [part(can("resume") ? "Resume" : "Pause")] : []),
        ...(can("request-changes") ? [part("Request changes")] : []),
        part("⋮", "muted"),
      ]
      const actions = labels.flatMap((label, index) => (index ? [part("   "), label] : [label]))
      const changed = `${agent.files.length} ${agent.files.length === 1 ? "file" : "files"} changed ▸`
      const children: { size?: number; node: UiNode }[] = [
        {
          size: 1,
          node: bodyLine(
            text([
              segments([
                part(
                  `  ${detail?.summary.map((line) => (line.kind === "segments" ? line.parts.map((part) => part.text).join("") : line.text)).join(" ") || agent.task}`,
                  "muted",
                ),
              ]),
            ]),
          ),
        },
      ]
      if (agent.status === "done" && agent.durationMs !== undefined && !narrow)
        children.push({
          size: 1,
          node: bodyLine(text([segments([part(`  done in ${duration(agent.durationMs)}`, "muted")])])),
        })
      if (agent.files.length) {
        if (!narrow) children.push({ size: 1, node: bodyLine(text([])) })
        children.push({ size: 1, node: bodyLine(text([segments([part("  Changed files", "muted")])])) })
        for (const file of agent.files.slice(0, narrow ? 1 : 3))
          children.push({
            size: 1,
            node: bodyLine(text([segments([part("  "), ...fileParts(file, Math.min(52, innerWidth - 2))])])),
          })
        if (agent.files.length > (narrow ? 1 : 3))
          children.push({
            size: 1,
            node: bodyLine(
              text([
                segments([part(`  +${agent.files.length - (narrow ? 1 : 3)} more · o open diff`, "muted")]),
              ]),
            ),
          })
      }
      if (last) {
        if (!narrow) children.push({ size: 1, node: bodyLine(text([])) })
        children.push({
          size: 1,
          node: bodyLine({
            type: "bar",
            left: [part(count, "muted")],
            right: narrow
              ? []
              : [part("e expand all · o diff · p pause/resume · r changes · a actions", "muted")],
          }),
        })
        children.push({ size: 1, node: frame("╰", "╯") })
      } else children.push({ size: 1, node: bodyLine({ type: "rule" }) })
      items.push({
        key: `agent:${agent.id}`,
        node: [part(last && phaseIndex === phases.length - 1 ? "└─" : "├─", "muted")],
        row: [
          part(foldedFooter ? "─╰ " : "─▶ ", "muted"),
          part(`${mark[agent.status]} `, tone(agent.status)),
          part(field(agent.name, narrow ? 10 : 12), "accent"),
          ...(!narrow
            ? [
                part(`  ${field(agent.task, 22)}  `),
                ...(agent.language
                  ? [
                      { kind: "chip" as const, text: agent.language, tone: "info" as const },
                      part(" ".repeat(Math.max(2, 16 - Bun.stringWidth(agent.language) - 2))),
                    ]
                  : [part(" ".repeat(16))]),
              ]
            : [part(" ")]),
          part(
            `${bar}  ${progress === undefined ? "—" : `${Math.round(progress * 100)}%`}`,
            progress === undefined ? "muted" : tone(agent.status),
          ),
          ...(foldedFooter ? [part(` ${"─".repeat(innerWidth)}`, "muted")] : []),
        ],
        aside: [
          ...(foldedFooter
            ? [part(`${count} · e expand all`, "muted")]
            : !narrow
              ? [part(`${agent.files.length ? changed : "no changes"}  │  `, "muted"), ...actions]
              : [part(" o diff", "accent")]),
          part(foldedFooter ? " ╯ " : " │ ", "muted"),
        ],
        rail: true,
        detail: { type: "column", children },
        underline: last,
      })
    }
  }
  const tree: UiNode = { type: "tree", id: "timeline", expanded: "all", items }
  const height = items.reduce(
    (sum, item) =>
      sum +
      1 +
      Number(!!item.underline) +
      (open(item.key) && item.detail && !Array.isArray(item.detail)
        ? item.detail.type === "column"
          ? item.detail.children.reduce((sum, child) => sum + Number(child.size ?? 1), 0)
          : 1
        : 0),
    0,
  )
  // Carry the rail through spare timeline space rather than inserting blank gap rows.
  return height >= ctx.height
    ? tree
    : {
        type: "column",
        children: [
          { size: height, node: tree },
          {
            node: text(
              Array.from({ length: ctx.height - height }, () => segments([part("              │", "muted")])),
            ),
          },
        ],
      }
}

export function summary(source: DashboardSource, agent: DashboardAgent, ctx: UiContext): UiNode {
  const detail = source.details(agent.id)
  const usage = detail?.stats?.usage
  const tokens = usage ? usage.input + usage.output : undefined
  const runtime =
    agent.durationMs ??
    (agent.startedAt !== undefined && ["running", "paused", "idle"].includes(agent.status)
      ? ctx.now - agent.startedAt
      : undefined)
  const values = [
    ["Agent", agent.name],
    ["Task", agent.task],
    ["Kind", agent.language ?? "—"],
    ["Status", agent.status],
    ["Runtime", duration(runtime)],
    ["Started", clock(agent.startedAt)],
    [
      tokens === undefined ? "Cost" : "Tokens",
      `${tokens === undefined ? "" : `${(tokens / 1000).toFixed(1)}k · `}${agent.cost === undefined ? "unknown" : `$${agent.cost.toFixed(4)}`}`,
    ],
  ]
  const doing: ViewLine[] = [
    segments([part("What this agent is doing", "accent")]),
    ...(detail?.summary.length ? detail.summary : [{ kind: "text" as const, text: agent.task }]),
    ...(detail?.steps?.length
      ? [
          { kind: "text" as const, text: "" },
          segments([
            part(
              `Steps  ${detail.steps.map((step) => (step.status === "done" ? "✓" : step.status === "running" ? "›" : "•")).join("")} ${detail.steps.filter((step) => step.status === "done").length}/${detail.steps.length}`,
              "muted",
            ),
          ]),
          ...detail.steps.map((step) =>
            segments([
              part(
                `${step.status === "done" ? "✓" : step.status === "running" ? "›" : "•"} ${step.text}`,
                step.status === "done" ? "success" : "text",
              ),
            ]),
          ),
        ]
      : []),
  ]
  const notes = [
    ...(detail?.notes ?? []),
    ...(source.snapshot().warning ? [{ kind: "warning" as const, text: source.snapshot().warning! }] : []),
  ]
  if (ctx.width < 110)
    return text(
      [
        segments([part(`${agent.name} · ${agent.status} · ${duration(runtime)}`, "accent")]),
        { kind: "text", text: agent.task },
        ...doing.slice(1),
        { kind: "text", text: "" },
        ...values.slice(2).map(([key, value]) => segments([part(`${key!.padEnd(9)}${value}`)])),
        { kind: "text", text: "" },
        segments([part("Changed files", "accent")]),
        ...agent.files.map((file) => segments(fileParts(file, Math.max(1, ctx.width - 2)))),
        ...(!agent.files.length ? [{ kind: "muted" as const, text: "No files reported." }] : []),
        ...(notes.length
          ? [{ kind: "text" as const, text: "" }, segments([part("Notes", "accent")]), ...notes]
          : []),
      ],
      "summary",
    )
  return {
    type: "row",
    divider: true,
    gap: 1,
    children: [
      {
        size: 33,
        node: text(
          values.map(([key, value]) => segments([part(`${key!.padEnd(9)}${value}`)])),
          "summary",
        ),
      },
      { node: text(doing, "summary-activity") },
      {
        size: "28%",
        node: text(
          [
            segments([part("Changed files", "accent"), part(`  ${agent.files.length} files`, "muted")]),
            ...agent.files.map((file) =>
              segments(fileParts(file, Math.max(1, Math.floor((ctx.width - 4) * 0.28) - 2))),
            ),
            ...(!agent.files.length ? [{ kind: "muted" as const, text: "No files reported." }] : []),
            ...(notes.length
              ? [{ kind: "text" as const, text: "" }, segments([part("Notes", "accent")]), ...notes]
              : []),
          ],
          "summary-files",
        ),
      },
    ],
  }
}
